### ISSUE TITLE
VMAX array could not be collected at pyu4p v4.

### ISSUE THREAD

**Issue by jamestsai-mu** [dell/powermax-splunk-addon#7]
PowerMax serial devices are find and working.
But VMAX 250F did not be collected at pyu4p v4 version.

Array not performance registered or is not local to Unisphere. Exiting metrics collection run.
2022-12-20 10:26:55,401 ERROR pid=92386 tid=MainThread file=base_modinput.py:log_error:309 | Get error when collecting events.
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/py_lib_dir/aob_py3/modinput_wrapper/base_modinput.py", line 128, in stream_events
    self.collect_events(ew)
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/inputs.py", line 272, in collect_events
    input_module.collect_events(self, ew)
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/powermax_splunk_core/driver/powermax_input_module.py", line 47, in collect_events
    pmax = PMaxSplunk(helper=helper, event_writer=ew)
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/powermax_splunk_core/driver/powermax_splunk.py", line 51, in __init__
    self._validate_configuration()
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/powermax_splunk_core/driver/powermax_splunk.py", line 263, in _validate_configuration
    self.log_critical(msg, raise_exception=True, exc=EnvironmentError)
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/powermax_splunk_core/driver/powermax_splunk.py", line 430, in log_critical
    raise exc(log_msg)
OSError: Input: XXXXXVMAX2 | Array: 0002978XXXXX | Array not performance registered or is not local to Unisphere. Exiting metrics collection run.

Could you give me a hand? Thanks!

**Comment by sheehp3** [comment]
Array: 0002978XXXXX | Array not performance registered or is not local to Unisphere

This array is not collecting stats in Unisphere .

Log on to your instance of Unisphere and register this array for performance stats .

Wait about 20 mins for stats to be collected and see if you can graph a chart for this array in Unisphere in the Performance section . Once you  can do this you know that Unisphere has data for the array and you should be able to collect data then.

If you cannot draw a graph in Unisphere for the array you will not be able to collect performance stats in the Splunk addon

**Comment by sheehp3** [comment]
This is an issue with an array not collecting performance stats in unisphere

**Comment by jamestsai-mu** [comment]
Thanks, sheehps.
I had already registered the 250F performance in Unisphere. I can see the performance chart at U4P version 10.
But Splunk Add-on still could not collect data, also show i posted error message.
Thanks a lot!

**Comment by sheehp3** [comment]
Hi,

So can you just confirm that you have the latest version of the add on from splunkbase  and on what version of Splunk Enterprise you have the addon running?

Also can you give the version of unisphere you are running and the arrays and the microcode they are running.

At startup splunk performs a series of checks . The error you posted above is the array you are trying to get stats for is not registered or local for stats ?

So the arrays you are collecting stats for successfully are they managed by the same instance of Unisphere what microcode are they running ?

Can you send on details of what version of Unisphere you are running and details of the Arrays you are trying to gather stats on and what microcode they are running? 

I need the full picture of what is going on .

Do you have postman client or equivalent ?

Can you run the following rest calls to see if the array you are collecting stats for is showing up as registered in REST

GET call

{{protocol}}://{{server}}:{{port}}/univmax/restapi/performance/Array/registrationdetails/all

Sample Output:

{
    "registrationDetailsInfo": [
        {
            "symmetrixId": "000120200107",
            "realtime": true,
            "diagnostic": true,
            "file": false,
            "collectionintervalmins": 5,
            "message": "Success"
        },
        {
            "symmetrixId": "000297901493",
            "realtime": false,
            "diagnostic": false,
            "file": false,
            "collectionintervalmins": 5,
            "message": "Success"
        },
        {
            "symmetrixId": "000297901855",
            "realtime": false,
            "diagnostic": false,
            "file": false,
            "collectionintervalmins": 5,
            "message": "Success"
        }
    ]
}

If showing true for the Array . Then you need to do a keys call  which will tell you the last timestamp in the database you have data for in the database .

Rest Get Call;

{{protocol}}://{{server}}:{{port}}/univmax/restapi/performance/Array/keys
{
    "arrayInfo": [
        {
            "symmetrixId": "000120200107",
            "firstAvailableDate": 1671224520000,
            "lastAvailableDate": 1671549300000
        }
    ]

Convert the   "lastAvailableDate": 1671549300000 to your local time you can use something like 

https://www.epochconverter.com/

You need to ensure that the last timestamp is current and up to date with your splunk instance timestamp or it will fail checks.

If everything above is ok then you will have to send on unisphere smas log and splunk enterprise version and splunk addon version to me , Array type and microcode that is failing for you so I can investigate further .

Just to give you a heads up I'm going to away until the 5th jan so it will be in the new year before I'll be able to respond further

Phil

**Comment by jamestsai-mu** [comment]
Micron Confidential

Hi sir,
I answered the questions as below.
Could you help to check and give me a hand?
Thanks a lot!



Micron Confidential
From: Philip Sheehan ***@***.***>
Sent: Wednesday, December 21, 2022 6:45 PM
To: dell/powermax-splunk-addon ***@***.***>
Cc: James Tsai 蔡 金炎 ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [dell/powermax-splunk-addon] VMAX array could not be collected at pyu4p v4. (Issue #7)

CAUTION: EXTERNAL EMAIL. Do not click links or open attachments unless you recognize the sender and were expecting this message.


Hi,

So can you just confirm that you have the latest version of the add on from splunkbase and on what version of Splunk Enterprise you have the addon running?
Dell EMC PowerMax App for Splunk Enterprise 3.1.0

Also can you give the version of unisphere you are running and the arrays and the microcode they are running.
10.0.0.0(Release, Build 2, 2022-06-04 11:58:06)

At startup splunk performs a series of checks . The error you posted above is the array you are trying to get stats for is not registered or local for stats ?
ta_dellemc_vmax_inputs.log
***@***.***

So the arrays you are collecting stats for successfully are they managed by the same instance of Unisphere what microcode are they running ?
Yes, the PowerMax and VMAX are using 5978.711.711 microcode version. Also performance are working on U4P 10.0.0.
***@***.***



Can you send on details of what version of Unisphere you are running and details of the Arrays you are trying to gather stats on and what microcode they are running?
I need the full picture of what is going on .

Do you have postman client or equivalent ? No

Can you run the following rest calls to see if the array you are collecting stats for is showing up as registered in REST

GET call

{{protocol}}://{{server}}:{{port}}/univmax/restapi/performance/Array/registrationdetails/all

Sample Output:

{
"registrationDetailsInfo": [
{
"symmetrixId": "000120200107",
"realtime": true,
"diagnostic": true,
"file": false,
"collectionintervalmins": 5,
"message": "Success"
},
{
"symmetrixId": "000297901493",
"realtime": false,
"diagnostic": false,
"file": false,
"collectionintervalmins": 5,
"message": "Success"
},
{
"symmetrixId": "000297901855",
"realtime": false,
"diagnostic": false,
"file": false,
"collectionintervalmins": 5,
"message": "Success"
}
]
}

If showing true for the Array . Then you need to do a keys call which will tell you the last timestamp in the database you have data for in the database .

Rest Get Call;

{{protocol}}://{{server}}:{{port}}/univmax/restapi/performance/Array/keys
{
"arrayInfo": [
{
"symmetrixId": "000120200107",
"firstAvailableDate": 1671224520000,
"lastAvailableDate": 1671549300000
}
]

Convert the "lastAvailableDate": 1671549300000 to your local time you can use something like

https://www.epochconverter.com/<https://urldefense.com/v3/__https:/www.epochconverter.com/__;!!KZTdOCjhgt4hgw!5bloDDU7l-KZV33v4XGf_iAo7uj1Tmb7YxjWOMPa_qifK1aZBwV3AkBW22m7OTNwVcX2B9BY0KbRzrGTIEsnh0WX$>

You need to ensure that the last timestamp is current and up to date with your splunk instance timestamp or it will fail checks.

If everything above is ok then you will have to send on unisphere smas log and splunk enterprise version and splunk addon version to me , Array type and microcode that is failing for you so I can investigate further .

Just to give you a heads up I'm going to away until the 5th jan so it will be in the new year before I'll be able to respond further

Phil

-

**Comment by jamestsai-mu** [comment]
Hi team,
After reboot PowerMax service processor, the performance data could be collected normally.
It is a interesting.
Thanks for your help!
